INSERT INTO `marque` (`name`, `logo`) VALUES
('Abarth', '1-logo-abarth.png'),
('AC', '2-logo-ac.png'),
('Acura', '4-logo-acura.png'),
('Aixam', '5-logo-aixam.png'),
('Alfa Romeo', '7-logo-alfa-romeo.png'),
('Allard', '8-logo-allard.png'),
('Alpina', '9-logo-alpina.png'),
('Alpine', '10-logo-alpine.png'),
('Alta', '11-logo-alta.png'),
('Alvis', '12-logo-alvis.png'),
('Amilcar', '13-logo-amilcar.png'),
('Arista', '14-logo-arista.png'),
('Aro', '16-logo-aro.png'),
('Artega', '17-logo-artega.png'),
('Aston Martin', '19-logo-aston-martin.png'),
('Ats', '20-logo-ats.png'),
('Audi', '22-logo-audi.png'),
('Austin', '23-logo-austin.png'),
('Autobianchi', '26-logo-autobianchi.png'),
('Auverland', '27-logo-auverland.png'),
('Bedford', '28-logo-bedford.png'),
('Bellier', '29-logo-bellier.png'),
('Bentley', '30-logo-bentley.png'),
('Bertone', '32-logo-bertone.png'),
('Bizzarrini', '33-logo-bizzarrini.png'),
('BMW', '34-logo-bmw.png'),
('Brabham', '35-logo-brabham.png'),
('Brabus', '36-logo-brabus.png'),
('Brasier', '37-logo-brasier.png'),
('Bristol', '38-logo-bristol.png'),
('Bugatti', '40-logo-bugatti.png'),
('Buick', '41-logo-buick.png'),
('Cadillac', '42-logo-cadillac.png'),
('Carlsson', '44-logo-carlsson.png'),
('Caterham', '45-logo-caterham.png'),
('Chevrolet US', '47-logo-chevrolet.png'),
('Chrysler', '48-logo-chrysler.png'),
('Citroen', '50-logo-citroen.png'),
('Cobra', '51-logo-cobra.png'),
('Cooper', '53-logo-cooper.png'),
('Corvette', '55-logo-corvette.png'),
('Dacia', '57-logo-dacia.png'),
('Daewoo', '58-logo-daewoo.png'),
('Daihatsu', '60-logo-daihatsu.png'),
('Daimler', '61-logo-daimler.png'),
('Datsun', '63-logo-datsun.png'),
('De Tomaso', '64-logo-de-tomaso.png'),
('Delage', '65-logo-delage.png'),
('Delahaye', '66-logo-delahaye.png'),
('Dodge', '68-logo-dodge.png'),
('Donkervoort', '69-logo-donkervoort.png'),
('Duesenberg', '70-logo-duesenberg.png'),
('Edsel', '72-logo-edsel.png'),
('Facel Vega', '74-logo-facel-vega.png'),
('Ferrari', '75-logo-ferrari.png'),
('Fiat', '77-logo-fiat.png'),
('Fisker', '78-logo-fisker.png'),
('Ford US', '79-logo-ford.png'),
('Frazer Nash', '81-logo-frazer-nash.png'),
('Fso-Polski', '82-logo-fso-polski.png'),
('General Motors', '83-logo-general-motors.png'),
('Ghia', '84-logo-ghia.png'),
('GMC', '86-logo-gmc.png'),
('Gordini', '88-logo-gordini.png'),
('Hispano Suiza', '92-logo-hispano-suiza.png'),
('Hommell', '93-logo-hommell.png'),
('Honda', '94-logo-honda.png'),
('Horch', '95-logo-horch.png'),
('Hummer', '97-logo-hummer.png'),
('Hyundai', '98-logo-hyundai.png'),
('Imperial', '99-logo-imperial.png'),
('Infiniti', '100-logo-infiniti.png'),
('Innocenti', '101-logo-innocenti.png'),
('Invicta', '102-logo-invicta.png'),
('Isuzu', '103-logo-isuzu.png'),
('Ital Design', '104-logo-ital-design.png'),
('Iveco', '105-logo-iveco.png'),
('Jaguar', '106-logo-jaguar.png'),
('Jdm', '107-logo-jdm.png'),
('Jeep', '108-logo-jeep.png'),
('Jensen', '109-logo-jensen.png'),
('Kaiser', '110-logo-kaiser.png'),
('Kia', '111-logo-kia.png'),
('Koenigsegg', '112-logo-koenigsegg.png'),
('Ktm', '113-logo-ktm.png'),
('Kurtis', '114-logo-kurtis.png'),
('Lada', '115-logo-lada.png'),
('Lagonda', '116-logo-lagonda.png'),
('Lamborghini', '117-logo-lamborghini.png'),
('Lancia', '118-logo-lancia.png'),
('Land Rover', '119-logo-land-rover.png'),
('Laraki', '120-logo-laraki.png'),
('Lea-Francis', '121-logo-lea-francis.png'),
('Lexus', '123-logo-lexus.png'),
('Ligier', '124-logo-ligier.png'),
('Lincoln', '125-logo-lincoln.png'),
('Lotus', '128-logo-lotus.png'),
('Mahindra', '129-logo-mahindra.png'),
('Fournier-Marcadier', '131-logo-fournier-marcadier.png'),
('Maruti', '134-logo-maruti.png'),
('Maserati', '135-logo-maserati.png'),
('Maybach', '137-logo-maybach.png'),
('Mazda', '138-logo-mazda.png'),
('McLaren', '139-logo-mclaren.png'),
('Mega', '140-logo-mega.png'),
('Mercedes-Benz', '141-logo-mercedes.png'),
('Mercury', '142-logo-mercury.png'),
('Mg', '143-logo-mg.png'),
('Microcar', '144-logo-microcar.png'),
('Mini', '145-logo-mini.png'),
('Mitsubishi', '146-logo-mitsubishi.png'),
('Monica', '147-logo-monica.png'),
('Monteverdi', '148-logo-monteverdi.png'),
('Morgan', '149-logo-morgan.png'),
('Morris', '150-logo-morris.png'),
('Nash', '152-logo-nash.png'),
('Nissan', '153-logo-nissan.png'),
('Novitec Rosso', '154-logo-novitec-rosso.png'),
('Oldsmobile', '155-logo-oldsmobile.png'),
('Opel', '156-logo-opel.png'),
('Osca', '157-logo-osca.png'),
('Packard', '158-logo-packard.png'),
('Pagani', '159-logo-pagani.png'),
('Panhard', '161-logo-panhard.png'),
('Peerless', '162-logo-peerless.png'),
('Pegaso', '163-logo-pegaso.png'),
('Peugeot', '164-logo-peugeot.png'),
('Pgo', '165-logo-pgo.png'),
('Pininfarina', '166-logo-pininfarina.png'),
('Plymouth', '167-logo-plymouth.png'),
('Pontiac', '168-logo-pontiac.png'),
('Porsche', '169-logo-porsche.png'),
('Proton', '170-logo-proton.png'),
('Renault', '171-logo-renault.png'),
('Riley', '172-logo-riley.png'),
('Rinspeed', '173-logo-rinspeed.png'),
('Rolland Pilain', '174-logo-rolland-pilain.png'),
('Rolls Royce', '175-logo-rolls-royce.png'),
('Rondeau Jean', '176-logo-rondeau-jean.png'),
('Rover', '177-logo-rover.png'),
('Saab', '178-logo-saab.png'),
('Saturn', '179-logo-saturn.png'),
('Sbarro', '180-logo-sbarro.png'),
('Seat', '181-logo-seat.png'),
('Secma', '182-logo-secma.png'),
('Shelby', '183-logo-shelby.png'),
('Siata', '184-logo-siata.png'),
('Simca', '185-logo-simca.png'),
('Skoda', '186-logo-skoda.png'),
('Spyker', '188-logo-spyker.png'),
('SsangYong', '189-logo-ssangyong.png'),
('Stanguellini', '190-logo-stanguellini.png'),
('Stoewer', '191-logo-stoewer.png'),
('Studbaker', '192-logo-studbaker.png'),
('Subaru', '193-logo-subaru.png'),
('Sunbeam', '194-logo-sunbeam.png'),
('Suzuki', '196-logo-suzuki.png'),
('Talbot', '197-logo-talbot.png'),
('Tatra', '198-logo-tatra.png'),
('Tchaika', '199-logo-tchaika.png'),
('Techart', '200-logo-techart.png'),
('Tesla', '201-logo-tesla.png'),
('Tojeiro', '202-logo-tojeiro.png'),
('Toyota', '203-logo-toyota.png'),
('Tramontana', '204-logo-tramontana.png'),
('Trident', '205-logo-trident.png'),
('Triumph', '206-logo-triumph.png'),
('Vanwall', '207-logo-vanwall.png'),
('Venturi', '208-logo-venturi.png'),
('Veritas', '209-logo-veritas.png'),
('Volkswagen', '211-logo-volkswagen.png'),
('Volvo', '212-logo-volvo.png'),
('Westfield', '213-logo-westfield.png'),
('Wiesmann', '214-logo-wiesmann.png'),
('Willys Overland', '215-logo-willys-overland.png'),
('Yamaha', '216-logo-yamaha.png'),
('Zagato', '217-logo-zagato.png'),
('Zastava', '218-logo-zastava.png'),
('Zaz', '219-logo-zaz.png'),
('Zest', '220-logo-zest.png'),
('Austin Healey', '24-logo-austin-healey.png'),
('Umm', '242-logo-umm.png'),
('Tata', '243-logo-tata.png'),
('Bajaj', '244-logo-bajaj.png'),
('TVR', '245-logo-tvr.png');
